---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: <%= ENV["machine_port"] %>
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04  

verifier:
  name: inspec

suites:
  - name: IBM Java8
    run_list:
      recipe[test::ibmjava8]
  - name: IBM Java9
    run_list:
      recipe[test::ibmjava9]
      
