---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: <%= ENV["machine_port"] %>
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04  

verifier:
  name: inspec

suites:
  - name: ibmjava8
    run_list:
      recipe[test::ibmjava8]
    # attributes: { travis_java: { ibmjava8: { pinned_release: '1.8.0_sr4fp6' }}}
  - name: switcher
    run_list:
      recipe[test::jdk_switcher]
  
      
