language: generic
dist: trusty
sudo: false

env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chef/bin:/opt/chef/embedded/bin:/opt/chefdk/embedded/bin:$PATH"

addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
    
services: docker
    
before_install:
    - gem --version
    - gem install bundler  
    - gem install test-kitchen
    - gem install vagrant-wrapper
    - gem install kitchen-vagrant
  
install:
    - sudo dpkg -i vagrant_1.2.2_x86_64.deb
    - sudo vagrant plugin install vagrant-plugin-bundler

script: 
    - foodcritic recipes
    - sudo vagrant up
    - kitchen version
    - kitchen test
    - ls -l /usr/lib/jvm
    
 
