language: ruby
dist: trusty
sudo: required

env:
  global:
    - machine_user=travis
    - machine_pass=travis
    - machine_port=22
    - KITCHEN_YAML=.kitchen.travis.yml

rvm:
  - 2.2.2
  
addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk


before_install:
  - sudo usermod -p "`openssl passwd -1 'travis'`" travis
  - gem install kitchen-inspec
  - gem install berkshelf
  - kitchen init

script:
  - chef -v
  - kitchen -v
  - chef gem list inspec
  - bundle exec kitchen verify ubuntu

branches:
  only:
  - master    
  
after_failure:
  - cat /home/travis/builds/chandrams/test-cookbook/.kitchen/logs/kitchen.log
  - ls /home/travis/builds/chandrams/test-cookbook
 
