language: generic
dist: trusty
sudo: false

env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chef/bin:/opt/chef/embedded/bin:/opt/chefdk/embedded/bin:$PATH"

addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
    
before_install:
    - gem --version
    - gem install bundler  
    - gem install test-kitchen

script: 
    - foodcritic recipes
    - kitchen version
    - kitchen init
    - kitchen test
    - ls -l /usr/lib/jvm
    
 