language: generic
dist: trusty
sudo: false

env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chef/bin:/opt/chef/embedded/bin:/opt/chefdk/embedded/bin:$PATH"

addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk

script: 
    - foodcritic recipes