language: generic
dist: trusty
sudo: false

env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chef/bin:/opt/chef/embedded/bin:/opt/chefdk/embedded/bin:$PATH"

addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
    
bundler_args: --without='vagrant'
    
services: docker
    
before_install:
    - gem --version
    - gem install bundler  
    - gem install test-kitchen
    - gem install vagrant-wrapper
    - gem install kitchen-vagrant
  
script: 
    - foodcritic recipes
    - sudo vagrant up
    - kitchen version
    - kitchen test
    - ls -l /usr/lib/jvm
    
 
