language: ruby
dist: trusty
sudo: required

env:
  global:
    - machine_user=travis
    - machine_pass=travis
    - machine_port=22
    - KITCHEN_YAML=.kitchen.travis.yml

rvm:
  - 2.3.1
  
addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk


before_install:
  - sudo usermod -p "`openssl passwd -1 'travis'`" travis   
  

script:
  - bundle exec kitchen verify
  - ls /usr/lib/jvm
  - /usr/lib/jvm/java-8-ibm-amd64/bin/java -version
  - /usr/lib/jvm/java-9-ibm-amd64/bin/java -version
  - ls /tmp

branches:
  only:
  - test-branch1 
